/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_patients_get"];
        put?: never;
        /** Crear */
        post: operations["crear_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener */
        get: operations["obtener_patients__patient_id__get"];
        put?: never;
        post?: never;
        /**
         * Eliminar
         * @description Ley 21.719: derecho de supresión sobre el paciente (ejercido por el
         *     admin del grupo). FK con `on delete cascade` en db/schema.sql borra
         *     bitácora, medicamentos, resúmenes, mensajes IA y membresías. RLS
         *     `patients_delete` filtra a solo admins del grupo — si el usuario no lo es,
         *     la consulta afecta 0 filas y devuelve 404.
         */
        delete: operations["eliminar_patients__patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_patients__patient_id__entries_get"];
        put?: never;
        /** Crear */
        post: operations["crear_patients__patient_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar */
        delete: operations["eliminar_patients__patient_id__entries__entry_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar */
        patch: operations["actualizar_patients__patient_id__entries__entry_id__patch"];
        trace?: never;
    };
    "/patients/{patient_id}/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_patients__patient_id__medications_get"];
        put?: never;
        /** Crear */
        post: operations["crear_patients__patient_id__medications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/medications/{medication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar */
        patch: operations["actualizar_patients__patient_id__medications__medication_id__patch"];
        trace?: never;
    };
    "/patients/{patient_id}/medications/{medication_id}/desactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desactivar */
        post: operations["desactivar_patients__patient_id__medications__medication_id__desactivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/medications/{medication_id}/doses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Dosis */
        get: operations["listar_dosis_patients__patient_id__medications__medication_id__doses_get"];
        put?: never;
        /** Registrar Dosis */
        post: operations["registrar_dosis_patients__patient_id__medications__medication_id__doses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/medications/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proximas Dosis
         * @description Proyecta las próximas dosis en la ventana pedida a partir de
         *     `medications.horarios`. El cliente móvil agenda notificaciones locales
         *     (expo-notifications) con este resultado.
         *
         *     Nota: los medicamentos con solo `frecuencia_horas` (sin horarios fijos)
         *     aún no se proyectan aquí; requieren consultar la última dosis tomada.
         */
        get: operations["proximas_dosis_patients__patient_id__medications_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/medications/adherence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Adherencia */
        get: operations["adherencia_patients__patient_id__medications_adherence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_patients__patient_id__members_get"];
        put?: never;
        /** Invitar */
        post: operations["invitar_patients__patient_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover */
        delete: operations["remover_patients__patient_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preguntar */
        post: operations["preguntar_patients__patient_id__assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial
         * @description Historial del asistente para el paciente. Cada mensaje incluye sus
         *     `cited_entry_ids` — auditar la trazabilidad del KPI (>90% verificable)
         *     es una consulta directa sobre este endpoint.
         *
         *     RLS filtra por membresía del grupo, así que un cuidador solo ve el
         *     historial de sus pacientes; no hay que chequear en código.
         */
        get: operations["historial_patients__patient_id__assistant_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/assistant/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Mensaje */
        get: operations["obtener_mensaje_patients__patient_id__assistant_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Conversaciones
         * @description Agrupa los mensajes por `conversation_id`. La agregación se hace en
         *     Python (~decenas/cientos de mensajes por paciente en el peor caso del
         *     piloto — no justifica una vista SQL todavía). RLS filtra automáticamente.
         */
        get: operations["listar_conversaciones_patients__patient_id__assistant_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/assistant/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mensajes De Conversacion
         * @description Mensajes de una conversación en orden cronológico ascendente (natural
         *     de lectura). Cada mensaje trae sus `cited_entry_ids` para trazabilidad.
         */
        get: operations["mensajes_de_conversacion_patients__patient_id__assistant_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_patients__patient_id__summaries_get"];
        put?: never;
        /** Generar */
        post: operations["generar_patients__patient_id__summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/metrics/relevo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relevo Familiar
         * @description KPI de relevo familiar: cuántos autores distintos registraron entradas
         *     en la ventana. Se considera "relevo" >= 2 autores distintos por semana
         *     (>60% de pacientes con relevo es el KPI comprometido).
         *
         *     RLS filtra automáticamente: si el usuario no pertenece al grupo del
         *     paciente, la consulta ve 0 filas (mismo resultado que un paciente sin
         *     actividad, sin filtrar información).
         */
        get: operations["relevo_familiar_patients__patient_id__metrics_relevo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial
         * @description Quién ha accedido a los datos del paciente. Transparencia hacia el
         *     titular del dato (paciente y sus admins). Un caregiver o viewer NO ve
         *     esto: la policy `audit_read` lo restringe a admins del grupo.
         */
        get: operations["historial_patients__patient_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_centers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consent Estado
         * @description Devuelve la versión vigente de la política, su texto y el timestamp
         *     de aceptación del usuario (o null si aún no la aceptó).
         */
        get: operations["consent_estado_me_consent_get"];
        put?: never;
        /**
         * Consent Aceptar
         * @description Registra la aceptación. La versión enviada debe coincidir con la
         *     vigente — evita "aceptar" una versión antigua o inventada. Idempotente:
         *     reintentar no crea duplicados (PK compuesta user_id+version).
         */
        post: operations["consent_aceptar_me_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil Actual
         * @description Devuelve el perfil del usuario autenticado. Si aún no existe, lo crea
         *     vacío y lo devuelve — así el cliente siempre recibe la misma forma.
         */
        get: operations["perfil_actual_me_profile_get"];
        /** Actualizar Perfil */
        put: operations["actualizar_perfil_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Export */
        get: operations["data_export_me_data_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar Cuenta
         * @description Ley 21.719 art. 8 (derecho de supresión / cancelación).
         *
         *     Efectos:
         *       - Autoría de bitácora y de mensajes IA → usuario "eliminado".
         *       - Membresías del usuario borradas.
         *       - Pacientes de los que era único miembro → eliminados en cascada
         *         (nadie más puede acceder ni ejercer derechos sobre ellos).
         *       - Cuenta en auth.users eliminada.
         *
         *     La operación es irreversible.
         */
        delete: operations["eliminar_cuenta_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdherenceReport
         * @description Adherencia calculada sobre dosis registradas en el rango. No proyecta
         *     dosis esperadas: si la familia no registró, no cuenta como omisión.
         */
        AdherenceReport: {
            /**
             * Desde
             * Format: date-time
             */
            desde: string;
            /**
             * Hasta
             * Format: date-time
             */
            hasta: string;
            /** Total Dosis Registradas */
            total_dosis_registradas: number;
            /** Tomadas */
            tomadas: number;
            /** Omitidas */
            omitidas: number;
            /** Postpuestas */
            postpuestas: number;
            /** Porcentaje Adherencia */
            porcentaje_adherencia: number;
        };
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Respuesta */
            respuesta: string;
            /** Cited Entry Ids */
            cited_entry_ids: string[];
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
        };
        /** AssistantMessage */
        AssistantMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Pregunta */
            pregunta: string;
            /** Respuesta */
            respuesta: string;
            /** Cited Entry Ids */
            cited_entry_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AssistantQuery */
        AssistantQuery: {
            /** Pregunta */
            pregunta: string;
            /**
             * Ventana Dias
             * @default 30
             */
            ventana_dias: number;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** AuditEntry */
        AuditEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Accion */
            accion: string;
            /** Recurso Tipo */
            recurso_tipo: string;
            /** Recurso Id */
            recurso_id: string | null;
            /** Patient Id */
            patient_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CareMember
         * @description Miembro del grupo de cuidado tal como lo expone `list_care_members`.
         */
        CareMember: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "caregiver" | "viewer";
            /** Nombre */
            nombre?: string | null;
            /** Telefono */
            telefono?: string | null;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** Center */
        Center: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Tipo */
            tipo: string;
            /** Region */
            region: string;
            /** Comuna */
            comuna?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Telefono */
            telefono?: string | null;
        };
        /** ConsentAccept */
        ConsentAccept: {
            /** Version */
            version: string;
        };
        /** ConsentStatus */
        ConsentStatus: {
            /** Version Vigente */
            version_vigente: string;
            /** Texto */
            texto: string;
            /** Aceptada En */
            aceptada_en: string | null;
        };
        /**
         * ConversationSummary
         * @description Resumen para el listado. Sin `respuesta` para no cargar el payload.
         */
        ConversationSummary: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Primera Pregunta */
            primera_pregunta: string;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Ultimo
             * Format: date-time
             */
            ultimo: string;
            /** Total Mensajes */
            total_mensajes: number;
        };
        /**
         * DataExport
         * @description Todo lo que el sistema tiene del usuario autenticado (derecho de acceso
         *     y portabilidad, Ley 21.719). Formato estable para el front.
         */
        DataExport: {
            /**
             * Exportado En
             * Format: date-time
             */
            exportado_en: string;
            /** Usuario */
            usuario: {
                [key: string]: unknown;
            };
            /** Membresias */
            membresias: components["schemas"]["MembershipExport"][];
            /** Entradas Bitacora */
            entradas_bitacora: components["schemas"]["Entry"][];
            /** Mensajes Asistente */
            mensajes_asistente: components["schemas"]["AssistantMessage"][];
            /** Pacientes Creados */
            pacientes_creados: components["schemas"]["Patient"][];
        };
        /** Entry */
        Entry: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "nota" | "medicamento" | "sintoma" | "animo" | "otro" | "alimentacion" | "ejercicio";
            /** Content */
            content: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntryCreate */
        EntryCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "nota" | "medicamento" | "sintoma" | "animo" | "otro" | "alimentacion" | "ejercicio";
            /** Content */
            content: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice";
        };
        /** EntryUpdate */
        EntryUpdate: {
            /** Kind */
            kind?: ("nota" | "medicamento" | "sintoma" | "animo" | "otro" | "alimentacion" | "ejercicio") | null;
            /** Content */
            content?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Medication */
        Medication: {
            /** Nombre */
            nombre: string;
            /** Dosis */
            dosis?: string | null;
            /** Frecuencia Horas */
            frecuencia_horas?: number | null;
            /** Horarios */
            horarios?: string[];
            /** Notas */
            notas?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Activo
             * @default true
             */
            activo: boolean;
        };
        /** MedicationCreate */
        MedicationCreate: {
            /** Nombre */
            nombre: string;
            /** Dosis */
            dosis?: string | null;
            /** Frecuencia Horas */
            frecuencia_horas?: number | null;
            /** Horarios */
            horarios?: string[];
            /** Notas */
            notas?: string | null;
        };
        /** MedicationDose */
        MedicationDose: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Taken At */
            taken_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "tomada" | "omitida" | "postpuesta";
            /** Notas */
            notas?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MedicationDoseCreate */
        MedicationDoseCreate: {
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Taken At */
            taken_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "tomada" | "omitida" | "postpuesta";
            /** Notas */
            notas?: string | null;
        };
        /** MedicationUpdate */
        MedicationUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Dosis */
            dosis?: string | null;
            /** Frecuencia Horas */
            frecuencia_horas?: number | null;
            /** Horarios */
            horarios?: string[] | null;
            /** Notas */
            notas?: string | null;
            /** Activo */
            activo?: boolean | null;
        };
        /** MemberInvite */
        MemberInvite: {
            /** Email */
            email: string;
            /**
             * Role
             * @default caregiver
             * @enum {string}
             */
            role: "admin" | "caregiver" | "viewer";
        };
        /** MembershipExport */
        MembershipExport: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Patient */
        Patient: {
            /** Nombre */
            nombre: string;
            /** Fecha Nacimiento */
            fecha_nacimiento?: string | null;
            /** Notas */
            notas?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PatientCreate */
        PatientCreate: {
            /** Nombre */
            nombre: string;
            /** Fecha Nacimiento */
            fecha_nacimiento?: string | null;
            /** Notas */
            notas?: string | null;
        };
        /** Profile */
        Profile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre?: string | null;
            /** Telefono */
            telefono?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Telefono */
            telefono?: string | null;
        };
        /**
         * RelevoMetric
         * @description Relevo familiar (KPI comprometido: >60% de pacientes con ≥2 autores/semana).
         */
        RelevoMetric: {
            ventana: components["schemas"]["VentanaTemporal"];
            /** Total Entries */
            total_entries: number;
            /** Autores Distintos */
            autores_distintos: number;
            /** Cumple Kpi */
            cumple_kpi: boolean;
        };
        /** Summary */
        Summary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Desde
             * Format: date-time
             */
            desde: string;
            /**
             * Hasta
             * Format: date-time
             */
            hasta: string;
            /** Contenido */
            contenido: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UpcomingDose
         * @description Próxima dosis proyectada desde `medications.horarios`. La usa el cliente
         *     para agendar notificaciones locales (expo-notifications).
         */
        UpcomingDose: {
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Nombre */
            nombre: string;
            /** Dosis */
            dosis?: string | null;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VentanaTemporal */
        VentanaTemporal: {
            /**
             * Desde
             * Format: date-time
             */
            desde: string;
            /**
             * Hasta
             * Format: date-time
             */
            hasta: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_patients_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_patients_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_patients__patient_id__delete: {
        parameters: {
            query?: {
                /** @description Debe ser true para ejecutar */
                confirmar?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_patients__patient_id__entries_get: {
        parameters: {
            query?: {
                limit?: number;
                desde?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_patients__patient_id__entries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_patients__patient_id__entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_patients__patient_id__entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_patients__patient_id__medications_get: {
        parameters: {
            query?: {
                incluir_inactivos?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Medication"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_patients__patient_id__medications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Medication"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_patients__patient_id__medications__medication_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Medication"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_patients__patient_id__medications__medication_id__desactivar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Medication"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dosis_patients__patient_id__medications__medication_id__doses_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationDose"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_dosis_patients__patient_id__medications__medication_id__doses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationDoseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationDose"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proximas_dosis_patients__patient_id__medications_upcoming_get: {
        parameters: {
            query?: {
                within_hours?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingDose"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adherencia_patients__patient_id__medications_adherence_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdherenceReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_patients__patient_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareMember"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invitar_patients__patient_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareMember"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_patients__patient_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preguntar_patients__patient_id__assistant_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_patients__patient_id__assistant_messages_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Paginación por cursor: devuelve mensajes con created_at < antes_de */
                antes_de?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_mensaje_patients__patient_id__assistant_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_conversaciones_patients__patient_id__assistant_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mensajes_de_conversacion_patients__patient_id__assistant_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_patients__patient_id__summaries_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generar_patients__patient_id__summaries_post: {
        parameters: {
            query?: {
                dias?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relevo_familiar_patients__patient_id__metrics_relevo_get: {
        parameters: {
            query?: {
                /** @description ISO 8601; default = hace 7 días */
                desde?: string | null;
                /** @description ISO 8601; default = ahora */
                hasta?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelevoMetric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_patients__patient_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                antes_de?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_centers_get: {
        parameters: {
            query?: {
                region?: string | null;
                tipo?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Center"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consent_estado_me_consent_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consent_aceptar_me_consent_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    perfil_actual_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_perfil_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_export_me_data_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_cuenta_me_delete: {
        parameters: {
            query?: {
                /** @description Debe ser true para ejecutar */
                confirmar?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
